### ISSUE TITLE
Support angular-translate-loader-partial ?

### ISSUE THREAD

**Issue by Ronaldlp** [ajwhite/angular-translate-once#14]
Hi,
I'm using angular-translate-loader-partial since I've got multiple modules.
I've code something like below in my main module angular.config

```
$translatePartialLoaderProvider.addPart('home');
$translateProvider.useLoader('$translatePartialLoader', {
  urlTemplate: '/i18n/{part}/{lang}.json'
});
$translateProvider.preferredLanguage('en');
```

and, I'm adding another part in run block of other module
`$translatePartialLoader.addPart('contact');`

translate-once is not working in the new module that is being loaded.
It's working when I'm putting all translations in the json file specified in my main module angular.config.

Can you help me on this. Thanks in advance.

**Comment by atticoos** [comment]
After a brief look at https://github.com/angular-translate/angular-translate/issues/399, could you try adding `$translate.refresh()` in your app's `.run()` method? Let me know if this doesn't do it, I have not used the partial loaders with this myself

**Comment by Ronaldlp** [comment]
i already tried `$translate.refresh()` . Doesn't works.

**Comment by Ronaldlp** [comment]
I moved the below code from run block to ui router resolve and it's working now.
```
$translatePartialLoader.addPart('contact');
$translate.refresh()
```

**Comment by Ronaldlp** [comment]
I moved the below code from run block to ui router resolve and it's working now.

```
$translatePartialLoader.addPart('contact');
$translate.refresh()
```

Thank you very much for your support.

**Comment by atticoos** [comment]
:+1:
