### ISSUE TITLE
How to use, phantomjs TypeError undefined is not a function bind?

### ISSUE THREAD

**Issue by dabbank** [ajwhite/angular-translate-once#7]
Hi,

in application is it running fine: just loading once.js file  ( no angular.module registration)

but when running with phantomas I got issues:
  ["TypeError: 'undefined' is not a function (evaluating 'TranslateOnceAttributeDirective.bind(undefined, attribute)') - unknown

**Comment by atticoos** [comment]
Thanks for reporting! This has also been brought to attention in #4.

Right now this will require a [polyfill for bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill).

The goal is to remove the usage of `.bind` in this project

**Comment by runderworld** [comment]
I guess this can be closed for good! (though #4 was already solved with the polyfill previously)

https://github.com/ajwhite/angular-translate-once/commit/81e0bdb68db8fd8b354b520144a9c5d5db9ad361

**Comment by atticoos** [comment]
Great stuff @runderworld :clap: 

I'll release the new version this week :smiley:

**Comment by atticoos** [comment]
[v1.0.3](https://github.com/ajwhite/angular-translate-once/releases/tag/v1.0.3) has been released with the changes :+1:
